server:
  port: 8090

spring:
  profiles:
    active: dev
  application:
    name: statistics-service
  config:
    import: "optional:configserver:http://localhost:8091"
  
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka